### PR TITLE
Swift Package Manager support

### PR DESCRIPTION
**Pull request by mRs-**
I added Swift Package Manager support, but unfortunately I can't compile the Example Project.

`/Users/marius/Developer/iOS/Hero/Examples/HeroExamples/Examples/ImageGallery/ImageViewController.swift:67:38: Binary operator '+' cannot be applied to two 'CGPoint' operands`

maybe you can have a look @lkzhao

### CODE REVIEW

**Comment by lkzhao** [comment]
It won't compile because the example project is using the `CG+Hero.swift` file. Basically, that file is added to both the `Hero` framework target and the `HeroExamples` app target. Since you remove the Hero framework target and move it outside. You cannot add `CG+Hero.swift` into the example project's target anymore.

**Comment by lkzhao** [comment]
Removing the target will break Carthage support and won't display warnings for changes we make inside the `Hero` framework.
Can SPM work without removing the target?

**Comment by lkzhao** [comment]
I also thought SPM don't support iOS projects yet. Is that fixed now?

**Comment by mRs-** [comment]
SPM works with iOS but only when you are doing things manually at the moment. But IMO SPM will be heading in the right way and to support this right out of the box is a good addition. Especially if SPM works easier with iOS together

**Comment by mRs-** [comment]
now it should be everything ok :)

**Comment by lkzhao** [comment]
Awesome! Thank you! Can you tell me how to install this via the SPM? I have no experience using it. I can put this into the usage guide.

**Comment by mRs-** [comment]
I will update it tomorrow directly in the README.md 🍻

**Comment by lkzhao** [comment]
@mRs- Sure. Please add it here: https://github.com/lkzhao/Hero/wiki/Usage-Guide

**Comment by mRs-** [comment]
I'm done with adding it to the usage guide.

**Comment by lkzhao** [comment]
There are some conflicts. Can you resolve them? The files you moved are changed in the master branch. Guess you will have to move them again. Thanks!

**Comment by mRs-** [comment]
Done

**Pull request merged**
