### PR TITLE
[WIP] Refactor HeroModifiers into a swift enum

### PR DESCRIPTION
**Pull request by lkzhao**
#11 

Turns out to be a much bigger change than I intended.

### CODE REVIEW

**Comment by lkzhao** [comment]
Few things I did here:
* change the original `heroModifiers:String?` to `heroModifierString:String?`
* added **HeroModifier** enum and **HeroTargetState** struct
  * **HeroModifier** is a swift enum that is similar to what we have today.
  * **HeroTargetState** is a struct that holds view state informations. It can be build from **[HeroModifier]**
    When transition starts Hero converts views' modifiers into a targetState. This help me eliminated many internal spaghetti codes like:
    ```swift
    // want to check if the view wants specific zPosition
    // replaced this
    for modifier in modifiers {
      if case .zPosition(let zPosition) = modifier {
        // finally got the actual zPosition that I needed
      }
    }
    // with this
    targetState.zPosition
    ```
* added `heroModifiers:[HeroModifier]?` to `UIView`
* added a shard singleton `Hero` object for controlling the interactive transition. Which can be accessed by `Hero.shared`
* few changes to the protocols 
  * protocol **HeroAnimator**
     ```swift
     func temporarilySet(view:UIView, to modifiers:HeroModifiers)
     // to 
     func temporarilySet(view:UIView, targetState:HeroTargetState)
     // Note that this is mostly an internal protocol, or for building HeroPlugins.
     // for users, they still access `Hero.shared.temporarilySet(view:view, to:modifiers)`
     ```
  * protocol **HeroViewControllerDelegate**
     ```swift
     @objc optional func wantInteractiveHeroTransition(context:HeroInteractiveContext) -> Bool
     // to
     @objc optional func wantInteractiveHeroTransition() -> Bool
  * removed **HeroInteractiveContext** protocol
* updated `HeroPlugin` to conform to the new protocols definitions.

These protocol changes and the shared singleton was done to fix a problem introduced by switching to swift enum. Because for interactive transitions, A method in the **HeroInteractiveContext** is changed from
```swift
func temporarilySet(view:UIView, with modifiers:String)
```
to
```swift
func temporarilySet(view:UIView, modifiers:[HeroModifier])
```

Since **[HeroModifier]** cannot be represented in objective-c, **HeroInteractiveContext** have to be a pure swift protocol. This makes **HeroInteractiveContext** not representable in objective-c.  Hence, making the call in **HeroViewControllerDelegate** not representable, too.
```swift
@objc optional func wantInteractiveHeroTransition(context:HeroInteractiveContext) -> Bool
```
I don't want to convert **HeroViewControllerDelegate** into a pure swift protocol. That will force people implementing all methods of **HeroViewControllerDelegate**. Plus if we ever wanted to add objective-c support, these protocols become problems.

**Comment by lkzhao** [comment]
New usage examples:
```swift
view.heroModifiers = [.fade, .scale(x:0.5, y:0.5), .translate(x:0, y:500, z:0)]
```
or 
```swift
view.heroModifierString = ".fade .scale(0.5) .translate(0, 500)"
```

Both works.
**heroModifierString** is now a computed property for `heroModifiers`. When it is assigned, it parse the string and assigns the **heroModifiers**. You reversely access the **heroModifierString**, too. I used the method proposed by @evermeer

**Comment by kylebshr** [comment]
I was initially against `heroModifierString` but thinking about it, I'm all for keeping it. We now have the type safe enum array, but the string opens up doors to interesting possibilities, such as loading options from a networked API and applying them to the app.

**Comment by lkzhao** [comment]
Similar to what you said above. I would still like to keep the `heroModifierString`. I deprecated this property because I was trying to force people to use `heroModifiers` instead. But in swift there is no way to ignore warnings. It is a bit intrusive for people that may use this property for whatever reason.

The macro trick is not needed anymore if we are keeping `heroModifierString` accessible in code.

**Comment by kylebshr** [comment]
Yeah, I think we should either not deprecate it, or take it out completely with the macro. Just my 2¢

**Comment by lkzhao** [comment]
Yea, lets just leave it there and not deprecate it.

There is one thing I disliked about this implementation.
Enum doesn't support default value and doesn't allow method overloading with the same name.

The construction becomes a bit long for modifiers like:
```swift
.scale(x:0.5, y:0.5, z:1), .rotate(x:0, y:0, z:π), .translate(x:100, y:100, z:0)
```

The z axis is probably not used most of the time but we have to provide the value non the less. And we have to remember that the default value for scale is 1, but 0 for rotate and translate.

I still love to be able to use the following:
```swift
.scale(0.5), .translate(x:100,y:100)
```

**Comment by lkzhao** [comment]
And the custom modifiers are ugly too.

I am thinking something like this:
```swift
public class HeroModifier2{
  private let apply:(inout HeroTargetState) -> Void
  public init(applyFunction:@escaping (inout HeroTargetState) -> Void){
    apply = applyFunction
  }

  static func scale(x:CGFloat, y:CGFloat = 1, z:CGFloat = 1) -> HeroModifier2 {
    return HeroModifier2 { targetState in
      targetState.transform = CATransform3DScale(targetState.transform ?? CATransform3DIdentity, x, y, z)
    }
  }

  static func scale(_ xy:CGFloat) -> HeroModifier2 {
    return HeroModifier2 { targetState in
      targetState.transform = CATransform3DScale(targetState.transform ?? CATransform3DIdentity, xy, xy, 1)
    }
  }
}
```

The usage would be nicer:
```swift
view.heroModifiers = [.scale(0.5), .translate(x:100)]
```

And you can easily extend to make custom modifiers
```
extension HeroModifier2{
  static func awesome(_ level:Int) -> HeroModifier2 {
    return HeroModifier2 { targetState in
      targetState["awesomeLevel"] = level
    }
  }
}

class AwesomePlugin:HeroPlugin{
  override func process(context: HeroContext, fromViews: [UIView], toViews: [UIView]) {
    for view in fromViews{
      if let level = context[view]?["awesomeLevel"] as? Int {
        print("\(view)'s awesome level is \(level)")
      }
    }
  }
}
```

**Comment by lkzhao** [comment]
Updated to use the new implementation. Dropped `heroModifierString` reverse lookup.

**Comment by mRs-** [comment]
You could drop the enum and create structs/classes with static init like the Color.clear method. This way you could create the short hand in the array with standard values for scale.

**Comment by lkzhao** [comment]
@mRs- yes, that's what I am doing now. Checkout the updated diff

**Comment by lkzhao** [comment]
I will merge this now. I will wait for everything to settle before publishing a new version. This is blocking some other fixes I am planning. If there is something you guys disliked. Feel free to let me know and we can sort it out before the next release.

**Pull request merged**
