### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by ayalcinkaya**

### CODE REVIEW

**Comment by lkzhao** [comment]
Thanks for contributing! I am sorry but I can't merge this. This is too big of a diff. Will be hard for me and others who are working on this project hard to merge our stuffs afterwards. 

I would keep it at two space indent for this project following the swift style guide [here](https://github.com/raywenderlich/swift-style-guide/blob/master/README.markdown)

**Comment by ayalcinkaya** [comment]
ok, your decision 👍🏻

**Comment by mRs-** [comment]
@lkzhao maybe you should add a contribution guideline

**Comment by lkzhao** [comment]
@ayalcinkaya Thank you for you understanding. 😊
@mRs- Sure

**Pull request closed without merging**
