### PR TITLE
PR to https://github.com/lkzhao/Hero/issues/348

### PR DESCRIPTION
**Pull request by dDomovoj**
Added HeroCompatible protocol with constrained HeroExtension.
Updated examples and sources

### CODE REVIEW

**Comment by dDomovoj** [comment]
Maybe in future releases it would be reasonable to delete deprecated functions and properties completely to keep IDE code completion more clean)

**Comment by lkzhao** [comment]
@dDomovoj This is awesome!!!!! Much more elegant. Just one small thing about `.hero.ID`, maybe we should change it to `.hero.id` in lowercase. what do you think?

**Comment by dDomovoj** [comment]
@lkzhao Sure) will append changes a bit later then

**Comment by dDomovoj** [comment]
@lkzhao Applied changes

**Comment by lkzhao** [comment]
Looks good to me. Really nice work!

**Pull request merged**
